# Generated by Django 4.2.4 on 2024-10-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "python_scripts",
            "0002_rename_author_jokes_category_remove_jokes_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jokes",
            name="delivery",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="jokes",
            name="joke",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="jokes",
            name="setup",
            field=models.TextField(blank=True, default=""),
        ),
    ]
